import '@/app/globals.css'
import { Toaster } from 'react-hot-toast';


export const metadata = {
  title: 'Tienda de Bicicletas',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  return (
    <html lang="es">
      <body> 
        {children}
        <Toaster position="top-right"  />
      </body>
    </html>
  )
}
